global:
  scrape_interval: 10s
  scrape_timeout:  10s
  evaluation_interval: 1s 

scrape_configs:
  - job_name: 'webserver'
    static_configs:
      - targets: ['webserver:5000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'system_runtime_threadpool_queue_length'
        action: drop
      - source_labels: [__name__]
        regex: 'system_runtime_cpu_usage'
        action: drop
      - source_labels: [__name__]
        regex: 'process_number_of_threads'
        action: drop
      - source_labels: [__name__]
        regex: 'busy_worker_threads'
        action: drop
  - job_name: 'node'
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'pushgateway'
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets: ['pushgateway:9091']
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"